const thumbs = ['13a5b79c49b610ed04f17f5f98c822cc7bae98d8e9a50be4a4f3271b030ef8c2','169d3a0152df28b59581d95296d6b89e17093d8efdf8aa5539213418f9673844','1a871f85e567d70d709377231fbe62248d31f17e3ad63b62d31691291147b8e2','1c7a00a610b82b5fb1a4bab4e539dfa07f80496d45a2bc84df2150d4a7d3ea32','21e61d13f9fdafc67c4ff9dfc64121f86e0cde616200e9fca593b7f51fc6e0a5','25a1730e3ad8ff2359ce8f831f685bf78dc6a40d09f6fda1eb766cd4feef9366','3a9d4ccd88c69bc2305281e00212326cd3557f58f3036cee8c2ba0273ebaad3e','3afab320f6653cc7b5bdc7d675b0e05e74f832c4c7009ab856aff06b3a64b08f','3b2fbef7bad03fc66fd0cb41a60984c687e3e4da373d4e139794f5ca014d2fd8','4020ff39b3bb95d9fa24e8cd197968e81d1008eb4e06c3e9decd024b9a137d7a','40d2d1a623d1e423e82880ae5e8035b5fb79a6f3ba74391436126d721f74781e','4509b7b748cc69e6b3686446640c39ee642d446b696757d0764bc71e8c182df7','4f708c9bed54f71bfc35bac18165e71c7a9c78d9a459258f893bc5a2b0f2b10a','5e9f1ddc582220d43aaf5b507455c9c4987e7d1cf06667acb79f4181559f14d6','5f97f877ae970f3d58868dcac3978d0312ab39c38f0b1f9a3b1e5d6c941334ad','6110db8f279ff20b056cafcc59b781b660d81f96e05dd072174c318d34196e9f'];
const names=['Purple columbine','Plated dessert','Seafood paella','Deep field','Ladybug','Fresh cream','Jaguar portrait','Mountain trail','Pigeon enclosure','Vidhana Soudha','Wedding celebration','Savanna landscape','City skyline','Stormy ocean','Snowy peak','Alpine lake'];
let items=thumbs.map((id,i)=>({id,name:names[i],fileName:`${id}.jpg`,src:`assets/${id}.jpg`,kind:'image',sensitive:false,tags:[],selected:false}));let current=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
// Album uses its own outlined/fill SVG set for navigation and viewer chrome.
const paths={photo_library:'M3 5h18v14H3z M6 8v8h12V8z',group:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm0-2a2 2 0 1 1 0-4 2 2 0 0 1 0 4Zm7-1a3 3 0 1 0 0-6v2a1 1 0 1 1 0 2v2ZM1 20v-2c0-3 3-5 7-5s7 2 7 5v2h-2v-2c0-1.5-2-3-5-3s-5 1.5-5 3v2h-2Zm15 0v-2c0-1-.3-2-.8-2.8 3.3.2 5.8 1.8 5.8 4.8h-5Z',collections_bookmark:'M4 4h16v16H4z M7 7v10h10V7z M8 15l2.5-3 2 2 1.5-2 2 3H8Z',movie:'M3 5h14v14H3z M17 9l4-2v10l-4-2z',music_note:'M9 18a3 3 0 1 1-2-2.83V5l11-2v12a3 3 0 1 1-2-2.83V7L9 8.3V18Z',description:'M5 2h10l4 4v16H5z M14 4v4h4 M8 12h8 M8 16h8',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3h-2V7a2 2 0 0 0-4 0v3z',settings:'M4 7h10v2H4z M18 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4ZM10 15h10v2H10z M6 14a2 2 0 1 1 0 4 2 2 0 0 1 0-4Z',search:'M9.5 3a6.5 6.5 0 1 0 4.05 11.58L18 19l1-1-4.42-4.45A6.5 6.5 0 0 0 9.5 3Zm0 2a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9Z',grid_view:'M3 3h8v8H3z M13 3h8v8h-8z M3 13h8v8H3z M13 13h8v8h-8z',view_quilt:'M3 3h7v11H3z M12 3h9v7h-9z M3 16h7v5H3z M12 12h9v9h-9z',more_horiz:'M5 10a2 2 0 1 0 0 4a2 2 0 1 0 0-4ZM12 10a2 2 0 1 0 0 4a2 2 0 1 0 0-4ZM19 10a2 2 0 1 0 0 4a2 2 0 1 0 0-4Z',edit:'M4 17.5V20h2.5L18 8.5 15.5 6z M14 7.5l2.5 2.5',share:'M8 12l8-7v4c4 0 6 3 6 8-2-3-4-4-6-4v4z M4 6v14h13',info:'M12 10v7M12 7v.1 M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0',close:'M5 5l14 14m0-14L5 19',crop:'M6 2v16a2 2 0 0 0 2 2h14 M2 6h14a2 2 0 0 1 2 2v14',rotate_right:'M4 10a8 8 0 1 1 2 7 M4 4v6h6',flip:'M3 4h8v16H3z M13 4h8v16h-8z'};
const strokes=new Set(['edit','share','info','close','crop','rotate_right','flip']);
$$('.material-symbols-rounded').forEach(el=>{let name=el.textContent.trim(),path=paths[name];if(path)el.outerHTML=`<svg class="line-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}" ${strokes.has(name)?'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"':'fill="currentColor" fill-rule="evenodd"'}/></svg>`});
function gallery(target, data=items){target.innerHTML=data.map(x=>{const index=items.indexOf(x);return `<article class="media-card${x.selected?' selected':''}" data-index="${index}"><img src="${x.src}" alt="" loading="lazy"><button class="media-selector" type="button" aria-label="${x.selected?'Remove from':'Add to'} selection" aria-pressed="${x.selected?'true':'false'}"><span class="material-symbols-rounded">${x.selected?'check':'circle'}</span></button></article>`}).join('');target.querySelectorAll('.media-card').forEach(card=>{card.onclick=event=>{const index=+card.dataset.index;if(event.target.closest('.media-selector')){event.stopPropagation();items[index].selected=!items[index].selected;gallery(target,data);document.dispatchEvent(new CustomEvent('album-selection-change'));return}openViewer(index)}});}
function openViewer(index){current=index;let x=items[index];$('#viewer-image').src=x.src;$('#viewer-name').textContent=x.fileName||x.name||'Photo';$('#viewer-meta').textContent=`${index+1} of ${items.length}`;$('#viewer').showModal();}
function switchPage(name){$$('.page,.nav').forEach(e=>e.classList.remove('active'));$(`#${name}`).classList.add('active');$$(`.nav[data-page="${name}"]`).forEach(e=>e.classList.add('active'));window.scrollTo(0,0);}
function toast(message){let e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
gallery($('#gallery'));
$$('[data-page]').forEach(e=>e.addEventListener('click',()=>switchPage(e.dataset.page)));
$('#search').addEventListener('input',e=>{let q=e.target.value.toLowerCase();gallery($('#gallery'),items.filter(x=>`${x.name} ${x.tags.join(' ')}`.toLowerCase().includes(q)));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#viewer').open)$('#viewer').close();});
$('.viewer-close').onclick=()=>$('#viewer').close();$('.previous').onclick=()=>openViewer((current+items.length-1)%items.length);$('.next').onclick=()=>openViewer((current+1)%items.length);
$('#layout-button').onclick=()=>{let g=$('#gallery'),square=g.classList.toggle('square-gallery'),name=square?'view_quilt':'grid_view';$('#layout-button').innerHTML=`<svg class="line-svg" viewBox="0 0 24 24"><path d="${paths[name]}" fill="currentColor"/></svg>`};
$$('.chip').forEach(c=>c.addEventListener('click',()=>{let row=c.parentElement;row.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}));
let people=[];$('#people-grid').innerHTML='';document.querySelector('#people .notice').hidden=true;$('#review-people').onclick=()=>modal('No suggestions to review','Suggested matches appear here only after Album has analyzed faces or pets.','Close');
let collectionNames=[];$('#collections-list').innerHTML='<div class="empty card"><h2>No collections yet</h2><p>Create albums and virtual groupings.</p><button class="button primary" id="empty-create-collection">Create collection</button></div>';$('#new-collection').onclick=()=>modal('New collection','Give this collection a name.','Create collection','Collection name');
$('#vault-search').oninput=e=>gallery($('#vault-gallery'),items.filter(x=>x.sensitive&&x.name.toLowerCase().includes(e.target.value.toLowerCase())));
function modal(title,description,action,placeholder,done){$('#modal-body').innerHTML=`<h2>${title}</h2><p>${description}</p>${placeholder?`<input placeholder="${placeholder}" ${placeholder.includes('password')?'type="password"':''} autofocus>`:''}<div style="display:flex;justify-content:flex-end;gap:8px"><button class="button" value="cancel">Cancel</button><button class="button primary" value="default">${action}</button></div>`;let d=$('#modal');d.showModal();d.querySelector('form').onsubmit=()=>done?.();}

// Browser equivalent of Album's photo editor: draw, rotate, zoom, and save a copy.
if(false){ // superseded by editor.js
const edit=$('#editor'),canvas=$('#edit-canvas'),ctx=canvas.getContext('2d');let editImage=null,originalEdit=null,originalEditSrc='',drawing=false,lastPoint=null,tool='none',cropStart=null,cropRect=null,cropBase=null,history=[],adjustBase=null;
function sourceImage(){let i=new Image();i.src=canvas.toDataURL('image/png');return i}
function snapshot(){if(!canvas.width||!canvas.height)return;history.push(canvas.toDataURL('image/png'));history=history.slice(-20)}
function drawImage(img){canvas.width=img.naturalWidth||img.width;canvas.height=img.naturalHeight||img.height;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0)}
function restore(src){let i=new Image();i.onload=()=>{editImage=i;drawImage(i)};i.src=src}
function renderEditor(){if(editImage)drawImage(editImage)}
function openEditor(){let x=items[current];editImage=new Image();editImage.onload=()=>{originalEdit=editImage;originalEditSrc=x.src;history=[];adjustBase=null;tool='none';cropBase=null;$('#editor-name').textContent=`Edit ${x.name}`;renderEditor();edit.showModal()};editImage.src=x.src;}
$('#viewer-image').ondblclick=openEditor;$('#close-editor').onclick=()=>edit.close();
$('.viewer-edit').onclick=openEditor;
$('#editor-undo').onclick=()=>{let prior=history.pop();if(prior)restore(prior)};$('#editor-reset').onclick=()=>{if(originalEditSrc)restore(originalEditSrc);adjustBase=null;history=[];tool='none';cropBase=null;$('#editor-markup').hidden=true};
function applyTransform(fn){snapshot();let off=document.createElement('canvas'),o=off.getContext('2d');fn(off,o);restore(off.toDataURL('image/png'))}
$$('.editor-tool[data-edit]').forEach(button=>button.onclick=()=>{let action=button.dataset.edit;if(action==='rotate')applyTransform((off,o)=>{off.width=canvas.height;off.height=canvas.width;o.translate(off.width,0);o.rotate(Math.PI/2);o.drawImage(canvas,0,0)});if(action==='mirror')applyTransform((off,o)=>{off.width=canvas.width;off.height=canvas.height;o.translate(off.width,0);o.scale(-1,1);o.drawImage(canvas,0,0)});if(action==='enhance')applyTransform((off,o)=>{off.width=canvas.width;off.height=canvas.height;o.filter='contrast(1.12) saturate(1.13)';o.drawImage(canvas,0,0)});if(action==='draw'){tool='draw';$('#editor-markup').hidden=false}if(action==='crop'){tool='crop';toast('Drag over the photo to crop.')}if(action==='text'){let value=prompt('Text to add:');if(value){snapshot();ctx.font=`${Math.max(24,canvas.width*.045)}px Segoe UI`;ctx.lineWidth=4;ctx.strokeStyle='#111';ctx.strokeText(value,canvas.width*.08,canvas.height*.12);ctx.fillStyle='#fff';ctx.fillText(value,canvas.width*.08,canvas.height*.12);editImage=sourceImage()}}});
const legacyMarkupDone=$('#markup-done');if(legacyMarkupDone)legacyMarkupDone.onclick=()=>{tool='none';$('#editor-markup').hidden=true};$$('[data-pen]').forEach(b=>b.onclick=()=>{$$('[data-pen]').forEach(x=>x.classList.remove('active-tool'));b.classList.add('active-tool');tool=b.dataset.pen});
canvas.addEventListener('pointerdown',e=>{let p=point(e);if(tool==='crop'){snapshot();cropBase=ctx.getImageData(0,0,canvas.width,canvas.height);cropStart=p;cropRect={x:p.x,y:p.y,w:0,h:0};canvas.setPointerCapture(e.pointerId);return}if(!['draw','pencil','pen','marker','highlighter','eraser'].includes(tool))return;snapshot();drawing=true;lastPoint=p;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{let p=point(e);if(cropStart){cropRect.w=p.x-cropStart.x;cropRect.h=p.y-cropStart.y;ctx.putImageData(cropBase,0,0);ctx.save();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.strokeRect(cropRect.x,cropRect.y,cropRect.w,cropRect.h);ctx.restore();return}if(!drawing)return;ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=$('#brush-color').value;ctx.globalAlpha=tool==='highlighter'?.28:1;ctx.lineWidth=tool==='marker'?18:tool==='highlighter'?24:+$('#brush-size').value;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(lastPoint.x,lastPoint.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';lastPoint=p});
canvas.addEventListener('pointerup',()=>{if(cropRect&&tool==='crop'){let r=cropRect;ctx.putImageData(cropBase,0,0);if(Math.abs(r.w)>8&&Math.abs(r.h)>8){let off=document.createElement('canvas');off.width=Math.abs(r.w);off.height=Math.abs(r.h);off.getContext('2d').drawImage(canvas,r.w<0?r.x+r.w:r.x,r.h<0?r.y+r.h:r.y,Math.abs(r.w),Math.abs(r.h),0,0,off.width,off.height);restore(off.toDataURL())}else{history.pop()}cropRect=null;cropStart=null;cropBase=null;tool='none'}drawing=false});
const adjustmentNames=['Exposure','Contrast','Highlights','Shadows','Saturation','Warmth','Tint','Sharpness','Fade','Vignette'];$('#editor-adjustments').innerHTML=adjustmentNames.map((name,i)=>`<button class="adjust-card" data-adjust="${name}"><img src="${items[i%items.length].src}" alt=""><span>${name}</span><input type="range" min="-100" max="100" value="0"></button>`).join('');
function captureAdjustmentBase(){let off=document.createElement('canvas');off.width=canvas.width;off.height=canvas.height;off.getContext('2d').drawImage(canvas,0,0);return off}
$$('.adjust-card input').forEach(input=>{input.onpointerdown=()=>{snapshot();adjustBase=captureAdjustmentBase()};input.oninput=e=>{if(!adjustBase){snapshot();adjustBase=captureAdjustmentBase()}let value=+e.target.value;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.filter=`brightness(${1+(value/180)}) contrast(${1+(value/120)}) saturate(${1+(value/100)})`;ctx.drawImage(adjustBase,0,0);ctx.filter='none'};input.onchange=()=>{editImage=sourceImage();adjustBase=null}});$('#actions-tab').onclick=()=>{$('#editor-actions').style.display='flex';$('#editor-adjustments').classList.remove('show');$('#actions-tab').classList.add('active');$('#adjust-tab').classList.remove('active')};$('#adjust-tab').onclick=()=>{$('#editor-actions').style.display='none';$('#editor-markup').hidden=true;$('#editor-adjustments').classList.add('show');$('#adjust-tab').classList.add('active');$('#actions-tab').classList.remove('active')};
$('#viewer-share').onclick=()=>modal('Share or export','Copy an image, email it, share it, or save a copy.','Save a copy');$('#viewer-info').onclick=()=>modal('Photo information',`${items[current].name}\n\nImage · Indexed by Album\nLocal file paths remain protected in this portfolio build.`, 'Close');$('#viewer-more').onclick=()=>modal('More options','Mark as sensitive or standard, manage protected categories, open in another app, or show the original file.','Close');$('#search-history').onclick=()=>toast('No recent searches');
function point(event){let r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*canvas.width/r.width,y:(event.clientY-r.top)*canvas.height/r.height}}
$('#save-edit').onclick=()=>{let link=document.createElement('a');link.download=`${items[current].name}-edited.png`;link.href=canvas.toDataURL('image/png');link.click();toast('Edited copy saved')};
}
// Mobile uses five destination tabs; desktop retains the complete sidebar.
document.addEventListener('DOMContentLoaded',()=>{
  const nav=document.createElement('nav');nav.className='mobile-nav';nav.setAttribute('aria-label','Album mobile navigation');
  const tabs=[['library','photo_library','Library'],['people','group','People'],['collections','collections_bookmark','Collections'],['vault','lock','Vault'],['settings','settings','Settings']];
  nav.innerHTML=tabs.map(([page,icon,label])=>`<button type="button" data-page="${page}" aria-label="${label}"><span class="material-symbols-rounded">${icon}</span><span>${label}</span></button>`).join('');
  document.body.appendChild(nav);
  nav.querySelectorAll('.material-symbols-rounded').forEach(el=>{const name=el.textContent.trim(),path=paths[name];if(path)el.outerHTML=`<svg class="line-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}" fill="currentColor"/></svg>`});
  const sync=()=>nav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',document.getElementById(button.dataset.page)?.classList.contains('active')));
  nav.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;switchPage(button.dataset.page);sync();});sync();
});

/* Desktop-editor workflow for the browser version.  This replaces the early
   prototype handlers above with one self-contained editor controller. */
if(false){ // superseded by the audited desktop-parity controller
(()=>{
  const dialog=document.getElementById('editor'),stage=document.getElementById('editor-stage');
  const oldCanvas=document.getElementById('edit-canvas'),canvas=oldCanvas.cloneNode(true);oldCanvas.replaceWith(canvas);
  const ctx=canvas.getContext('2d'),image=document.getElementById('viewer-image'),cropOverlay=document.getElementById('crop-overlay'),textLayer=document.getElementById('text-layer');
  const ink=document.createElement('canvas');ink.id='edit-ink';stage.insertBefore(ink,textLayer);const inkCtx=ink.getContext('2d');
  let original='',history=[],mode='actions',pen='pencil',color='#ffffff',textColor='#ffffff',drawing=false,last=null,crop=null,cropStart=null,cropRatio=null,cropDrag=null,textEntry=null,adjustBase=null,adjustValues={},activeAdjust='Exposure';
  const adjustments=['Exposure','Contrast','Highlights','Shadows','Saturation','Warmth','Tint','Sharpness','Fade','Vignette'];
  const photo=(src,done)=>{const im=new Image();im.onload=()=>done(im);im.src=src;};
  const positionInk=()=>{const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect();Object.assign(ink.style,{left:`${r.left-s.left}px`,top:`${r.top-s.top}px`,width:`${r.width}px`,height:`${r.height}px`});};
  const saveState=()=>{if(canvas.width)history.push({image:canvas.toDataURL('image/png'),ink:ink.toDataURL('image/png')});if(history.length>24)history.shift();};
  const restoreInk=src=>photo(src,im=>{inkCtx.clearRect(0,0,ink.width,ink.height);inkCtx.drawImage(im,0,0);});
  const redraw=(src,done)=>photo(src,im=>{canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0);if(ink.width!==canvas.width||ink.height!==canvas.height){ink.width=canvas.width;ink.height=canvas.height}requestAnimationFrame(positionInk);done&&done();});
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};};
  const setMode=next=>{mode=next;document.getElementById('editor-actions').style.display=next==='actions'?'flex':'none';document.getElementById('editor-adjustments').classList.toggle('show',next==='adjust');document.getElementById('editor-markup').hidden=next!=='markup';document.getElementById('editor-text').hidden=next!=='text';document.getElementById('crop-context').hidden=next!=='crop';document.querySelector('.editor-tabs').style.display=['actions','adjust'].includes(next)?'flex':'none';document.getElementById('actions-tab').classList.toggle('active',next==='actions');document.getElementById('adjust-tab').classList.toggle('active',next==='adjust');cropOverlay.hidden=next!=='crop'||!crop;};
  const renderCrop=()=>{if(!crop){cropOverlay.hidden=true;return}const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),sx=cr.width/canvas.width,sy=cr.height/canvas.height;Object.assign(cropOverlay.style,{left:`${cr.left-sr.left+crop.x*sx}px`,top:`${cr.top-sr.top+crop.y*sy}px`,width:`${crop.w*sx}px`,height:`${crop.h*sy}px`});cropOverlay.hidden=false;};
  const normalizedCrop=()=>{if(!crop)return null;let{x,y,w,h}=crop;if(w<0){x+=w;w=-w}if(h<0){y+=h;h=-h}return{x:Math.max(0,x),y:Math.max(0,y),w:Math.min(w,canvas.width-x),h:Math.min(h,canvas.height-y)};};
  const reset=()=>{history=[];adjustValues={};adjustBase=null;crop=null;cropOverlay.hidden=true;textLayer.replaceChildren();textEntry=null;redraw(original,()=>inkCtx.clearRect(0,0,ink.width,ink.height));toast('Edits reset');};
  const open=()=>{original=image.src;history=[];adjustValues={};adjustBase=null;crop=null;textLayer.replaceChildren();textEntry=null;redraw(original,()=>setMode('actions'));dialog.showModal();};
  document.querySelector('.viewer-edit').onclick=open;
  document.getElementById('close-editor').onclick=()=>dialog.close();document.getElementById('editor-reset').onclick=reset;
  document.getElementById('editor-undo').onclick=()=>{const prior=history.pop();if(prior)redraw(prior.image,()=>restoreInk(prior.ink));else toast('Nothing to undo');};
  document.getElementById('save-edit').onclick=()=>{commitText();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;out.getContext('2d').drawImage(canvas,0,0);out.getContext('2d').drawImage(ink,0,0);const a=document.createElement('a');a.download=`${(typeof items!=='undefined'&&items[current]?.name)||'photo'}-edited.png`;a.href=out.toDataURL('image/png');a.click();toast('Edited copy saved');};
  function rotate(){saveState();const off=document.createElement('canvas');off.width=canvas.height;off.height=canvas.width;const c=off.getContext('2d');c.translate(off.width,0);c.rotate(Math.PI/2);c.drawImage(canvas,0,0);redraw(off.toDataURL());}
  function mirror(){saveState();ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(canvas,0,0);ctx.setTransform(1,0,0,1,0,0);}
  function enhance(){saveState();const off=document.createElement('canvas');off.width=canvas.width;off.height=canvas.height;const c=off.getContext('2d');c.filter='contrast(1.12) saturate(1.13) brightness(1.03)';c.drawImage(canvas,0,0);redraw(off.toDataURL());toast('Auto enhance applied');}
  function copy(){canvas.toBlob(async blob=>{try{await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('Image copied')}catch{toast('Your browser does not allow image clipboard access')}});}
  document.getElementById('editor-actions').onclick=e=>{const action=e.target.closest('[data-album-action]')?.dataset.albumAction;if(!action)return;if(action==='crop'){crop={x:canvas.width*.18,y:canvas.height*.18,w:canvas.width*.64,h:canvas.height*.64};cropRatio=null;renderCrop();setMode('crop')}else if(action==='rotate')rotate();else if(action==='mirror')mirror();else if(action==='markup')setMode('markup');else if(action==='text')setMode('text');else if(action==='enhance')enhance();else if(action==='reset')reset();else if(action==='copy')copy();};
  document.getElementById('actions-tab').onclick=()=>setMode('actions');document.getElementById('adjust-tab').onclick=()=>setMode('adjust');
  document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{cropRatio=b.dataset.ratio==='free'?null:b.dataset.ratio==='original'?canvas.width/canvas.height:+b.dataset.ratio;document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b));});
  document.getElementById('crop-cancel').onclick=()=>{crop=null;cropOverlay.hidden=true;setMode('actions')};document.getElementById('crop-done').onclick=()=>{const r=normalizedCrop();if(!r||r.w<3||r.h<3){toast('Drag a crop area first');return}saveState();const off=document.createElement('canvas'),inkOff=document.createElement('canvas');off.width=inkOff.width=Math.round(r.w);off.height=inkOff.height=Math.round(r.h);off.getContext('2d').drawImage(canvas,r.x,r.y,r.w,r.h,0,0,off.width,off.height);inkOff.getContext('2d').drawImage(ink,r.x,r.y,r.w,r.h,0,0,inkOff.width,inkOff.height);crop=null;cropOverlay.hidden=true;redraw(off.toDataURL(),()=>{restoreInk(inkOff.toDataURL());setMode('actions')});};
  canvas.addEventListener('pointerdown',e=>{const p=point(e);if(mode==='crop'){const r=normalizedCrop();if(r&&p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h){cropDrag={x:p.x-r.x,y:p.y-r.y}}else{cropStart=p;crop={x:p.x,y:p.y,w:0,h:0}}canvas.setPointerCapture(e.pointerId);renderCrop();return}if(mode==='text'){makeText(p);return}if(mode!=='markup')return;saveState();drawing=true;last=p;canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(mode==='crop'&&(cropStart||cropDrag)){const p=point(e);if(cropDrag){crop.x=Math.max(0,Math.min(canvas.width-crop.w,p.x-cropDrag.x));crop.y=Math.max(0,Math.min(canvas.height-crop.h,p.y-cropDrag.y))}else{let w=p.x-cropStart.x,h=p.y-cropStart.y;if(cropRatio){const signW=Math.sign(w)||1,signH=Math.sign(h)||1;if(Math.abs(w)/Math.max(Math.abs(h),1)>cropRatio)h=Math.abs(w)/cropRatio*signH;else w=Math.abs(h)*cropRatio*signW}crop={x:cropStart.x,y:cropStart.y,w,h}}renderCrop();return}if(!drawing)return;const p=point(e);inkCtx.save();inkCtx.lineCap=pen==='marker'||pen==='highlighter'?'square':'round';inkCtx.lineJoin='round';inkCtx.globalCompositeOperation=pen==='eraser'?'destination-out':'source-over';inkCtx.globalAlpha=pen==='highlighter'?.28:pen==='marker'?.55:pen==='pencil'?.75:1;inkCtx.strokeStyle=color;inkCtx.lineWidth=+document.getElementById('brush-size').value*(pen==='marker'?1.8:pen==='highlighter'?2.5:pen==='pencil'?.7:1);inkCtx.beginPath();inkCtx.moveTo(last.x,last.y);inkCtx.lineTo(p.x,p.y);inkCtx.stroke();inkCtx.restore();last=p;});
  const stop=e=>{if(mode==='crop'){cropStart=null;cropDrag=null;renderCrop()}drawing=false;if(e?.pointerId!==undefined&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);new ResizeObserver(positionInk).observe(stage);
  document.getElementById('editor-markup').onclick=e=>{const b=e.target.closest('[data-album-pen]');if(!b)return;pen=b.dataset.albumPen;document.querySelectorAll('[data-album-pen]').forEach(x=>x.classList.toggle('active-tool',x===b));};
  document.querySelectorAll('.color-swatches[data-color-target="brush"] button').forEach(b=>b.onclick=()=>{color=b.dataset.color;document.querySelectorAll('.color-swatches[data-color-target="brush"] button').forEach(x=>x.classList.toggle('active',x===b));});
  function makeText(p){commitText();const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),el=document.createElement('div');el.className='text-entry';el.contentEditable='true';Object.assign(el.style,{left:`${cr.left-sr.left+p.x*cr.width/canvas.width}px`,top:`${cr.top-sr.top+p.y*cr.height/canvas.height}px`,fontFamily:document.getElementById('text-font').value,fontSize:`${document.getElementById('text-size').value}px`,color:textColor,fontWeight:document.querySelector('[data-text-style="bold"]').classList.contains('active')?'700':'400',fontStyle:document.querySelector('[data-text-style="italic"]').classList.contains('active')?'italic':'normal',textDecoration:document.querySelector('[data-text-style="underline"]').classList.contains('active')?'underline':'none'});textLayer.append(el);textEntry=el;el.focus();}
  function commitText(){if(!textEntry||!textEntry.textContent.trim()){textEntry?.remove();textEntry=null;return}saveState();const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),x=(parseFloat(textEntry.style.left)-(cr.left-sr.left))*canvas.width/cr.width,y=(parseFloat(textEntry.style.top)-(cr.top-sr.top))*canvas.height/cr.height;const cs=getComputedStyle(textEntry);ctx.save();ctx.fillStyle=cs.color;ctx.font=`${cs.fontStyle} ${cs.fontWeight} ${parseFloat(cs.fontSize)*canvas.width/cr.width}px ${cs.fontFamily}`;ctx.textBaseline='top';textEntry.textContent.split('\n').forEach((line,i)=>ctx.fillText(line,x,y+i*parseFloat(cs.fontSize)*1.2*canvas.width/cr.width));ctx.restore();textEntry.remove();textEntry=null;}
  document.querySelectorAll('[data-finish-mode]').forEach(b=>b.onclick=()=>{if(b.dataset.finishMode==='text')commitText();setMode('actions')});
  document.querySelectorAll('.color-swatches[data-color-target="text"] button').forEach(b=>b.onclick=()=>{textColor=b.dataset.color;document.querySelectorAll('.color-swatches[data-color-target="text"] button').forEach(x=>x.classList.toggle('active',x===b));if(textEntry)textEntry.style.color=textColor;});
  document.querySelectorAll('[data-text-style]').forEach(b=>b.onclick=()=>{b.classList.toggle('active');if(textEntry){const s=b.dataset.textStyle;textEntry.style[s==='bold'?'fontWeight':s==='italic'?'fontStyle':'textDecoration']=b.classList.contains('active')?(s==='bold'?'700':s==='italic'?'italic':'underline'):(s==='bold'?'400':s==='italic'?'normal':'none')}});
  document.getElementById('text-size').oninput=e=>{if(textEntry)textEntry.style.fontSize=`${e.target.value}px`};document.getElementById('text-font').onchange=e=>{if(textEntry)textEntry.style.fontFamily=e.target.value};
  const browser=document.getElementById('adjust-browser');browser.innerHTML=adjustments.map((n,i)=>`<button class="adjust-card" data-adjust="${n}"><img src="assets/${thumbs[i%thumbs.length]}.jpg" alt=""><span>${n}</span></button>`).join('');
  const applyAdjust=()=>{if(!adjustBase)return;photo(adjustBase.toDataURL(),im=>{ctx.clearRect(0,0,canvas.width,canvas.height);const v=n=>(adjustValues[n]||0);ctx.filter=`brightness(${1+v('Exposure')/100}) contrast(${1+v('Contrast')/100}) saturate(${1+v('Saturation')/100})`;ctx.drawImage(im,0,0);ctx.filter='none';const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),d=pixels.data,hi=v('Highlights')/100,sh=v('Shadows')/100,sharp=v('Sharpness')/100;for(let i=0;i<d.length;i+=4){const l=(d[i]+d[i+1]+d[i+2])/765;if(l>.55){const q=hi*(l-.55)*.9;d[i]+=q*(255-d[i]);d[i+1]+=q*(255-d[i+1]);d[i+2]+=q*(255-d[i+2])}if(l<.48){const q=sh*(.48-l)*.95;d[i]+=q*(255-d[i]);d[i+1]+=q*(255-d[i+1]);d[i+2]+=q*(255-d[i+2])}if(sharp){const mid=l*255;d[i]+=((d[i]-mid)*sharp*.18);d[i+1]+=((d[i+1]-mid)*sharp*.18);d[i+2]+=((d[i+2]-mid)*sharp*.18)}}ctx.putImageData(pixels,0,0);if(v('Warmth')||v('Tint')||v('Fade')||v('Vignette')){ctx.save();if(v('Warmth')){ctx.globalCompositeOperation='soft-light';ctx.globalAlpha=Math.abs(v('Warmth'))/250;ctx.fillStyle=v('Warmth')>0?'#ffb35c':'#5c9dff';ctx.fillRect(0,0,canvas.width,canvas.height)}if(v('Tint')){ctx.globalCompositeOperation='soft-light';ctx.globalAlpha=Math.abs(v('Tint'))/260;ctx.fillStyle=v('Tint')>0?'#ff5da2':'#48d4a4';ctx.fillRect(0,0,canvas.width,canvas.height)}if(v('Fade')){ctx.globalAlpha=v('Fade')/180;ctx.fillStyle='#d7d1c7';ctx.fillRect(0,0,canvas.width,canvas.height)}if(v('Vignette')){const g=ctx.createRadialGradient(canvas.width/2,canvas.height/2,canvas.width*.16,canvas.width/2,canvas.height/2,canvas.width*.72);g.addColorStop(0,'transparent');g.addColorStop(1,`rgba(0,0,0,${Math.max(0,v('Vignette'))/115})`);ctx.globalAlpha=1;ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.restore();}})};
  browser.onclick=e=>{const b=e.target.closest('[data-adjust]');if(!b)return;activeAdjust=b.dataset.adjust;if(!adjustBase){saveState();const off=document.createElement('canvas');off.width=canvas.width;off.height=canvas.height;off.getContext('2d').drawImage(canvas,0,0);adjustBase=off}document.getElementById('adjust-label').textContent=activeAdjust;document.getElementById('adjust-slider').value=adjustValues[activeAdjust]||0;document.getElementById('adjust-value').textContent=adjustValues[activeAdjust]||0;browser.hidden=true;document.getElementById('adjust-focus').hidden=false;};
  document.getElementById('adjust-slider').oninput=e=>{adjustValues[activeAdjust]=+e.target.value;document.getElementById('adjust-value').textContent=e.target.value;applyAdjust()};document.getElementById('adjust-back').onclick=()=>{browser.hidden=false;document.getElementById('adjust-focus').hidden=true;adjustBase=null;};
})();
}
