(()=>{
  'use strict';
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const dialog=q('#editor'),stage=q('#editor-stage'),canvas=q('#edit-canvas'),ctx=canvas.getContext('2d');
  const cropEl=q('#crop-overlay'),textLayer=q('#text-layer'),actions=q('#editor-actions'),adjustPanel=q('#editor-adjustments');
  const cropContext=q('#crop-context'),deck=q('.editor-deck');dialog.insertBefore(cropContext,deck);
  const ink=document.createElement('canvas');ink.id='edit-ink';stage.insertBefore(ink,cropEl);const inkCtx=ink.getContext('2d');
  const toolDefs=[
    ['pencil','Pencil','stylus_pencil',3],['pen','Pen','stylus_fountain_pen',7],['marker','Marker','stylus_pen',14],
    ['highlighter','Highlighter','stylus_highlighter',22],['brush','Brush','stylus_brush',12],['eraser','Eraser','ink_eraser',24]
  ];
  const colors=['#ffffff','#ff3344','#ffc83d','#fff21f','#35d7c4','#3998ee','#2858ff','#922cff','#151515'];
  const adjustNames=['Exposure','Contrast','Highlights','Shadows','Saturation','Warmth','Tint','Sharpness','Fade','Vignette'];
  let originalSrc='',mode='actions',history=[],strokes=[],activeStroke=null,tool='pen',toolColor='#ff3344',toolWidth=7;
  let crop=null,cropAction=null,cropAspect=null,adjustValues=Object.fromEntries(adjustNames.map(n=>[n,0])),adjustBase=null,adjustSnapshotTaken=false;
  let activeAdjustment='Exposure',textEntry=null;

  function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src;});}
  function cloneStrokes(){return strokes.map(s=>({...s,points:s.points.map(p=>({...p}))}));}
  function snapshot(){history.push({image:canvas.toDataURL('image/png'),strokes:cloneStrokes()});if(history.length>20)history.shift();}
  function canvasPoint(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*canvas.width/r.width,y:(event.clientY-r.top)*canvas.height/r.height,pressure:event.pointerType==='mouse'||!event.pressure?0.5:Math.max(.12,event.pressure)};}
  function positionLayers(){if(!canvas.width)return;const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect();for(const layer of [ink])Object.assign(layer.style,{left:`${r.left-s.left}px`,top:`${r.top-s.top}px`,width:`${r.width}px`,height:`${r.height}px`});renderCrop();}
  function resizeInk(clear=true){if(ink.width===canvas.width&&ink.height===canvas.height){if(clear)inkCtx.clearRect(0,0,ink.width,ink.height);return}const previous=document.createElement('canvas');previous.width=ink.width;previous.height=ink.height;if(!clear)previous.getContext('2d').drawImage(ink,0,0);ink.width=canvas.width;ink.height=canvas.height;if(!clear)inkCtx.drawImage(previous,0,0,ink.width,ink.height);}
  async function setImage(src,{clearInk=false}={}){const image=await loadImage(src);canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);resizeInk(clearInk);requestAnimationFrame(positionLayers);}
  function compositeCanvas(){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const outCtx=out.getContext('2d');outCtx.drawImage(canvas,0,0);outCtx.drawImage(ink,0,0);return out;}
  function refreshInk(){resizeInk();inkCtx.clearRect(0,0,ink.width,ink.height);for(const stroke of strokes)drawStroke(stroke);}
  function smoothPath(points){const path=new Path2D();if(!points.length)return path;path.moveTo(points[0].x,points[0].y);if(points.length===2){path.lineTo(points[1].x,points[1].y);return path}for(let i=1;i<points.length-1;i++){const mid={x:(points[i].x+points[i+1].x)/2,y:(points[i].y+points[i+1].y)/2};path.quadraticCurveTo(points[i].x,points[i].y,mid.x,mid.y)}path.lineTo(points.at(-1).x,points.at(-1).y);return path;}
  function drawStroke(stroke){
    if(!stroke.points.length)return;
    inkCtx.save();inkCtx.strokeStyle=stroke.color;inkCtx.fillStyle=stroke.color;inkCtx.lineJoin='round';inkCtx.lineCap=['marker','highlighter'].includes(stroke.tool)?'square':'round';
    if(stroke.points.length===1){inkCtx.globalAlpha=stroke.tool==='highlighter'?.32:stroke.tool==='pencil'?.76:1;inkCtx.beginPath();inkCtx.arc(stroke.points[0].x,stroke.points[0].y,Math.max(.75,stroke.width*.42),0,Math.PI*2);inkCtx.fill();inkCtx.restore();return;}
    if(stroke.tool==='pen'){
      const points=stroke.points;
      for(let i=1;i<points.length;i++){
        const previous=points[i-1],point=points[i],pressure=((previous.pressure??.5)+(point.pressure??.5))/2;
        const taper=i===1?.72:(stroke.finished&&i===points.length-1?.68:1);
        inkCtx.lineWidth=Math.max(1,stroke.width*(.68+pressure*.62)*taper);
        inkCtx.beginPath();inkCtx.moveTo(previous.x,previous.y);
        if(i<points.length-1){const next=points[i+1];inkCtx.quadraticCurveTo(point.x,point.y,(point.x+next.x)/2,(point.y+next.y)/2)}else inkCtx.lineTo(point.x,point.y);
        inkCtx.stroke();
      }
      inkCtx.restore();return;
    }
    const path=smoothPath(stroke.points);inkCtx.lineWidth=stroke.width;inkCtx.globalAlpha=stroke.tool==='highlighter'?.32:stroke.tool==='pencil'?.76:1;if(stroke.tool==='brush'){inkCtx.shadowColor=stroke.color;inkCtx.shadowBlur=Math.max(1,stroke.width*.32)}inkCtx.stroke(path);inkCtx.restore();
  }
  function eraseAt(point){const radius=Math.max(8,toolWidth*1.2),next=[];for(const stroke of strokes){let part=[];for(const sample of stroke.points){if((sample.x-point.x)**2+(sample.y-point.y)**2>radius**2)part.push(sample);else if(part.length>1){next.push({...stroke,points:part});part=[]}}if(part.length>1)next.push({...stroke,points:part})}strokes=next;refreshInk();}
  function setMode(next){mode=next;actions.hidden=next!=='actions';adjustPanel.classList.toggle('show',next==='adjust');q('#editor-markup').hidden=next!=='markup';q('#editor-text').hidden=next!=='text';q('#crop-context').hidden=next!=='crop';q('.editor-tabs').hidden=!['actions','adjust'].includes(next);q('#actions-tab').classList.toggle('active',next==='actions');q('#adjust-tab').classList.toggle('active',next==='adjust');cropEl.hidden=next!=='crop';document.body.classList.toggle('album-editing',dialog.open);}
  async function openEditor(){originalSrc=q('#viewer-image').src;history=[];strokes=[];adjustValues=Object.fromEntries(adjustNames.map(n=>[n,0]));adjustBase=null;adjustSnapshotTaken=false;textLayer.replaceChildren();textEntry=null;await setImage(originalSrc,{clearInk:true});q('#editor-name').textContent=`Edit ${items[current].name}`;setMode('actions');dialog.showModal();document.body.classList.add('album-editing');document.documentElement.classList.add('album-editing');requestAnimationFrame(positionLayers);}
  function closeEditor(){dialog.close();document.body.classList.remove('album-editing');document.documentElement.classList.remove('album-editing');}

  function cropHandles(){return{lt:[crop.x,crop.y],t:[crop.x+crop.w/2,crop.y],rt:[crop.x+crop.w,crop.y],r:[crop.x+crop.w,crop.y+crop.h/2],rb:[crop.x+crop.w,crop.y+crop.h],b:[crop.x+crop.w/2,crop.y+crop.h],lb:[crop.x,crop.y+crop.h],l:[crop.x,crop.y+crop.h/2]};}
  function beginCrop(aspect=null){cropAspect=aspect==='original'?canvas.width/canvas.height:aspect;const margin=Math.max(18,Math.min(canvas.width,canvas.height)/12);let w=canvas.width-margin*2,h=canvas.height-margin*2;if(cropAspect){if(w/h>cropAspect)w=h*cropAspect;else h=w/cropAspect}crop={x:(canvas.width-w)/2,y:(canvas.height-h)/2,w,h};setMode('crop');renderCrop();}
  function renderCrop(){if(mode!=='crop'||!crop){cropEl.hidden=true;return}const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect(),sx=r.width/canvas.width,sy=r.height/canvas.height;Object.assign(cropEl.style,{left:`${r.left-s.left+crop.x*sx}px`,top:`${r.top-s.top+crop.y*sy}px`,width:`${crop.w*sx}px`,height:`${crop.h*sy}px`});cropEl.hidden=false;}
  function hitCrop(point){const tolerance=18*canvas.width/Math.max(1,canvas.getBoundingClientRect().width);for(const [name,[x,y]] of Object.entries(cropHandles()))if(Math.hypot(point.x-x,point.y-y)<=tolerance)return name;return point.x>=crop.x&&point.x<=crop.x+crop.w&&point.y>=crop.y&&point.y<=crop.y+crop.h?'move':null;}
  function dragCrop(point){const a=cropAction,start=a.start,dx=point.x-a.press.x,dy=point.y-a.press.y;let x=start.x,y=start.y,w=start.w,h=start.h;if(a.handle==='move'){x+=dx;y+=dy}else{if(a.handle.includes('l')){x=start.x+dx;w=start.w-dx}if(a.handle.includes('r'))w=start.w+dx;if(a.handle.includes('t')){y=start.y+dy;h=start.h-dy}if(a.handle.includes('b'))h=start.h+dy;if(cropAspect){if(['l','r'].includes(a.handle)){h=w/cropAspect;y=start.y+(start.h-h)/2}else if(['t','b'].includes(a.handle)){w=h*cropAspect;x=start.x+(start.w-w)/2}else{const useWidth=Math.abs(dx)>=Math.abs(dy);if(useWidth)h=w/cropAspect;else w=h*cropAspect;if(a.handle.includes('l'))x=start.x+start.w-w;if(a.handle.includes('t'))y=start.y+start.h-h}}}w=Math.max(40,Math.min(canvas.width,w));h=Math.max(40,Math.min(canvas.height,h));x=Math.max(0,Math.min(canvas.width-w,x));y=Math.max(0,Math.min(canvas.height-h,y));crop={x,y,w,h};renderCrop();}
  async function applyCrop(){snapshot();const base=document.createElement('canvas'),newStrokes=[];base.width=Math.round(crop.w);base.height=Math.round(crop.h);base.getContext('2d').drawImage(canvas,crop.x,crop.y,crop.w,crop.h,0,0,base.width,base.height);for(const stroke of strokes){const points=stroke.points.map(p=>({x:p.x-crop.x,y:p.y-crop.y})).filter(p=>p.x>=0&&p.y>=0&&p.x<=crop.w&&p.y<=crop.h);if(points.length>1)newStrokes.push({...stroke,points})}strokes=newStrokes;await setImage(base.toDataURL(),{clearInk:true});refreshInk();crop=null;setMode('actions');}

  function buildCropUI(){cropEl.innerHTML='<div class="crop-grid"></div>'+['lt','t','rt','r','rb','b','lb','l'].map(h=>`<i class="crop-handle crop-${h}" aria-hidden="true"></i>`).join('');qa('[data-ratio]').forEach(button=>button.onclick=()=>{qa('[data-ratio]').forEach(b=>b.classList.toggle('active',b===button));const value=button.dataset.ratio;beginCrop(value==='free'?null:value==='original'?'original':+value)});q('#crop-cancel').onclick=()=>{crop=null;setMode('actions')};q('#crop-done').onclick=applyCrop;}
  function buildMarkupUI(){const panel=q('#editor-markup');panel.innerHTML=`<button class="bare-icon mode-done" data-markup-done aria-label="Done with markup"><span class="material-symbols-rounded">arrow_back</span></button><div class="markup-tools">${toolDefs.map(([id,label,icon])=>`<button class="editor-tool${id==='pen'?' active-tool':''}" data-markup-tool="${id}"><span class="markup-icon material-symbols-rounded">${icon}</span><span>${label}</span></button>`).join('')}</div><label class="markup-size">Size <input type="range" id="brush-size" min="1" max="48" value="7"><output>7</output></label><div class="color-swatches">${colors.map((c,i)=>`<button class="${i===1?'active':''}" data-markup-color="${c}" style="--swatch:${c}" aria-label="${c}"></button>`).join('')}</div>`;panel.onclick=event=>{const toolButton=event.target.closest('[data-markup-tool]'),colorButton=event.target.closest('[data-markup-color]');if(event.target.closest('[data-markup-done]'))setMode('actions');if(toolButton){tool=toolButton.dataset.markupTool;toolWidth=toolDefs.find(d=>d[0]===tool)[3];q('#brush-size').value=toolWidth;q('.markup-size output').value=toolWidth;qa('[data-markup-tool]').forEach(b=>b.classList.toggle('active-tool',b===toolButton));refreshMarkupSelection()}if(colorButton){toolColor=colorButton.dataset.markupColor;qa('[data-markup-color]').forEach(b=>b.classList.toggle('active',b===colorButton));refreshMarkupSelection()}};q('#brush-size').oninput=event=>{toolWidth=+event.target.value;q('.markup-size output').value=toolWidth};}
  function refreshMarkupSelection(){qa('[data-markup-tool]').forEach(button=>{const selected=button.dataset.markupTool===tool;button.classList.toggle('active-tool',selected);button.style.setProperty('--active-tool-color',selected&&tool!=='eraser'?toolColor:'#e7e7ea')});}

  function buildAdjustUI(){const browser=q('#adjust-browser'),focus=q('#adjust-focus');browser.innerHTML=adjustNames.map(name=>`<button class="adjust-card" data-adjust="${name}"><img alt=""><span>${name}</span></button>`).join('');focus.innerHTML='<button class="bare-icon" id="adjust-back" aria-label="Back to adjustments"><span class="material-symbols-rounded">arrow_back</span></button><label id="adjust-label" for="adjust-slider">Exposure · 0</label><input id="adjust-slider" type="range" min="-100" max="100" value="0"><button class="button" id="adjust-reset-one">Reset adjustment</button>';browser.onclick=event=>{const button=event.target.closest('[data-adjust]');if(!button)return;activeAdjustment=button.dataset.adjust;q('#adjust-label').textContent=`${activeAdjustment} · ${adjustValues[activeAdjustment]}`;q('#adjust-slider').value=adjustValues[activeAdjustment];browser.hidden=true;focus.hidden=false};q('#adjust-back').onclick=()=>{focus.hidden=true;browser.hidden=false;updateAdjustThumbs()};q('#adjust-slider').oninput=event=>{if(!adjustBase){adjustBase=canvas.toDataURL();if(!adjustSnapshotTaken){snapshot();adjustSnapshotTaken=true}}adjustValues[activeAdjustment]=+event.target.value;q('#adjust-label').textContent=`${activeAdjustment} · ${event.target.value}`;applyAdjustments()};q('#adjust-reset-one').onclick=()=>{q('#adjust-slider').value=0;adjustValues[activeAdjustment]=0;q('#adjust-label').textContent=`${activeAdjustment} · 0`;applyAdjustments()};}
  function updateAdjustThumbs(){const src=canvas.toDataURL(),filters={Exposure:'brightness(1.3)',Contrast:'contrast(1.5)',Saturation:'saturate(1.7)',Sharpness:'contrast(1.12)'};qa('.adjust-card').forEach(card=>{const img=card.querySelector('img');img.src=src;img.style.filter=filters[card.dataset.adjust]||'none'});}
  async function applyAdjustments(){if(!adjustBase)return;const image=await loadImage(adjustBase);ctx.clearRect(0,0,canvas.width,canvas.height);const v=name=>adjustValues[name]/100;ctx.filter=`brightness(${2**v('Exposure')}) contrast(${Math.max(.05,1+v('Contrast'))}) saturate(${Math.max(0,1+v('Saturation'))})`;ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.filter='none';const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),data=pixels.data;for(let i=0;i<data.length;i+=4){const lum=(data[i]+data[i+1]+data[i+2])/765,high=v('Highlights'),shadow=v('Shadows'),warm=v('Warmth'),tint=v('Tint'),sharp=v('Sharpness');if(lum>.5){const amount=high*(lum-.5)*.7;for(let c=0;c<3;c++)data[i+c]=Math.max(0,Math.min(255,high>=0?data[i+c]+(255-data[i+c])*amount:data[i+c]*(1+amount)))}if(lum<.5){const factor=Math.max(.2,1+shadow*.18);for(let c=0;c<3;c++)data[i+c]*=factor}data[i]*=1+.18*warm;data[i+2]*=1-.18*warm;data[i+1]*=1+.12*tint;const mid=lum*255;for(let c=0;c<3;c++)data[i+c]+=(data[i+c]-mid)*sharp}
    ctx.putImageData(pixels,0,0);const fade=Math.max(0,v('Fade')),vignette=Math.max(0,v('Vignette'));if(fade){ctx.save();ctx.globalAlpha=fade*.18;ctx.fillStyle='#d8d3ca';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}if(vignette){const gradient=ctx.createRadialGradient(canvas.width/2,canvas.height/2,Math.min(canvas.width,canvas.height)*.18,canvas.width/2,canvas.height/2,Math.max(canvas.width,canvas.height)*.65);gradient.addColorStop(0,'transparent');gradient.addColorStop(1,`rgba(0,0,0,${vignette*.88})`);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height)}}

  function resetEditor(){history=[];strokes=[];adjustValues=Object.fromEntries(adjustNames.map(n=>[n,0]));adjustBase=null;adjustSnapshotTaken=false;textLayer.replaceChildren();setImage(originalSrc,{clearInk:true});setMode('actions');toast('Edits reset');}
  async function undo(){const state=history.pop();if(!state){toast('Nothing to undo');return}strokes=state.strokes;await setImage(state.image,{clearInk:true});refreshInk();adjustBase=null;adjustSnapshotTaken=false;}
  async function rotate(){snapshot();const off=document.createElement('canvas');off.width=canvas.height;off.height=canvas.width;const out=off.getContext('2d');out.translate(off.width,0);out.rotate(Math.PI/2);out.drawImage(canvas,0,0);strokes=strokes.map(s=>({...s,points:s.points.map(p=>({x:canvas.height-p.y,y:p.x}))}));await setImage(off.toDataURL(),{clearInk:true});refreshInk();}
  async function mirror(){snapshot();const off=document.createElement('canvas');off.width=canvas.width;off.height=canvas.height;const out=off.getContext('2d');out.translate(off.width,0);out.scale(-1,1);out.drawImage(canvas,0,0);strokes=strokes.map(s=>({...s,points:s.points.map(p=>({x:canvas.width-p.x,y:p.y}))}));await setImage(off.toDataURL(),{clearInk:true});refreshInk();}
  function createText(point){if(textEntry)commitText();textEntry=document.createElement('div');textEntry.className='text-entry';textEntry.contentEditable='true';textEntry.textContent='Type text';const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect();Object.assign(textEntry.style,{left:`${r.left-s.left+point.x*r.width/canvas.width}px`,top:`${r.top-s.top+point.y*r.height/canvas.height}px`});textLayer.append(textEntry);textEntry.focus();document.execCommand?.('selectAll',false,null);}
  function commitText(){if(!textEntry)return;const value=textEntry.textContent.trim(),r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect();if(value){snapshot();const x=(parseFloat(textEntry.style.left)-(r.left-s.left))*canvas.width/r.width,y=(parseFloat(textEntry.style.top)-(r.top-s.top))*canvas.height/r.height;ctx.save();ctx.font=`${Math.max(16,canvas.width*.045)}px Segoe UI`;ctx.lineWidth=Math.max(2,canvas.width*.003);ctx.strokeStyle='#111';ctx.fillStyle='#fff';ctx.strokeText(value,x,y);ctx.fillText(value,x,y);ctx.restore()}textEntry.remove();textEntry=null;}

  buildCropUI();buildMarkupUI();buildAdjustUI();refreshMarkupSelection();
  q('#adjust-browser').addEventListener('wheel',event=>{if(Math.abs(event.deltaY)>Math.abs(event.deltaX)){event.currentTarget.scrollLeft+=event.deltaY;event.preventDefault()}},{passive:false});
  q('.viewer-edit').onclick=openEditor;q('#viewer-image').ondblclick=openEditor;q('#close-editor').onclick=closeEditor;q('#editor-undo').onclick=undo;q('#editor-reset').onclick=resetEditor;
  q('#save-edit').onclick=()=>{commitText();const link=document.createElement('a');link.download=`${items[current].name}-edited.png`;link.href=compositeCanvas().toDataURL('image/png');link.click();toast('Edited copy saved')};
  q('#actions-tab').onclick=()=>setMode('actions');q('#adjust-tab').onclick=()=>{setMode('adjust');q('#adjust-browser').hidden=false;q('#adjust-focus').hidden=true;updateAdjustThumbs()};
  actions.onclick=event=>{const action=event.target.closest('[data-album-action]')?.dataset.albumAction;if(!action)return;if(action==='crop')beginCrop();if(action==='rotate')rotate();if(action==='mirror')mirror();if(action==='markup')setMode('markup');if(action==='text')setMode('text');if(action==='reset')resetEditor();if(action==='copy')compositeCanvas().toBlob(async blob=>{try{await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('Image copied')}catch{toast('Clipboard access was blocked')}});if(action==='enhance'){if(!adjustBase){snapshot();adjustBase=canvas.toDataURL();adjustSnapshotTaken=true}adjustValues.Contrast=12;adjustValues.Saturation=13;adjustValues.Exposure=4;applyAdjustments();toast('Auto enhance applied')}};
  canvas.addEventListener('pointerdown',event=>{const point=canvasPoint(event);if(mode==='crop'){const handle=hitCrop(point);if(handle){cropAction={handle,press:point,start:{...crop}};canvas.setPointerCapture(event.pointerId)}return}if(mode==='markup'){snapshot();if(tool==='eraser'){activeStroke='erase';eraseAt(point)}else{activeStroke={tool,color:toolColor,width:toolWidth,points:[point]};strokes.push(activeStroke)}canvas.setPointerCapture(event.pointerId);return}if(mode==='text')createText(point)});
  canvas.addEventListener('pointermove',event=>{const point=canvasPoint(event);if(mode==='crop'&&cropAction){dragCrop(point);return}if(mode==='markup'&&activeStroke){if(activeStroke==='erase')eraseAt(point);else{for(const sample of event.getCoalescedEvents?.()||[event]){const next=canvasPoint(sample),last=activeStroke.points.at(-1);if((next.x-last.x)**2+(next.y-last.y)**2>=1.5)activeStroke.points.push(next)}refreshInk()}}});
  const release=event=>{cropAction=null;if(activeStroke&&activeStroke!=='erase'){activeStroke.finished=true;refreshInk()}activeStroke=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId)};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
  q('[data-finish-mode="text"]').onclick=()=>{commitText();setMode('actions')};window.addEventListener('resize',positionLayers);new ResizeObserver(positionLayers).observe(stage);dialog.addEventListener('close',()=>{document.body.classList.remove('album-editing');document.documentElement.classList.remove('album-editing')});
})();
