(()=>{
  'use strict';
  const q=selector=>document.querySelector(selector),qa=selector=>[...document.querySelectorAll(selector)];
  const semanticGroups=[
    ['portrait','person','people','face','character','figure'],['art','artwork','illustration','drawing','sketch','digital'],
    ['blue','ocean','water','sky','horizon'],['night','dark','moon','city','market'],['warm','golden','sun','summer','garden'],
    ['quiet','soft','calm','dream','study'],['armor','costume','reference','design']
  ];
  const scan={
    '13a5b79c49b610ed04f17f5f98c822cc7bae98d8e9a50be4a4f3271b030ef8c2':{description:'A close-up purple columbine flower with green stems and a softly blurred garden background.',colors:['purple','green'],tags:['flower','garden','macro','nature'],objects:['columbine','flower'],emotions:['calm']},
    '169d3a0152df28b59581d95296d6b89e17093d8efdf8aa5539213418f9673844':{description:'A small red plated dessert beside a fork and spoon on a white table.',colors:['white','red','silver'],tags:['dessert','food','minimal'],objects:['plate','dessert','fork','spoon'],emotions:[]},
    '1a871f85e567d70d709377231fbe62248d31f17e3ad63b62d31691291147b8e2':{description:'Seafood paella cooking outdoors in a large pan over an open flame.',colors:['yellow','orange','black'],tags:['food','cooking','outdoors'],objects:['paella','pan','seafood'],emotions:[]},
    '1c7a00a610b82b5fb1a4bab4e539dfa07f80496d45a2bc84df2150d4a7d3ea32':{description:'A deep-field space image filled with galaxies and bright diffraction spikes.',colors:['black','white','gold'],tags:['space','astronomy','galaxy'],objects:['galaxies','stars'],emotions:['wonder']},
    '21e61d13f9fdafc67c4ff9dfc64121f86e0cde616200e9fca593b7f51fc6e0a5':{description:'A red ladybug resting on the edge of a green leaf.',colors:['red','green','black'],tags:['insect','macro','nature'],objects:['ladybug','leaf'],emotions:['calm']},
    '25a1730e3ad8ff2359ce8f831f685bf78dc6a40d09f6fda1eb766cd4feef9366':{description:'Fresh white cream or curd spread across a metal plate.',colors:['white','silver','brown'],tags:['food','dairy'],objects:['cream','plate'],emotions:[]},
    '3a9d4ccd88c69bc2305281e00212326cd3557f58f3036cee8c2ba0273ebaad3e':{description:'A close wildlife portrait of a jaguar standing against dark rocks.',colors:['gold','black','gray'],tags:['wildlife','animal','portrait'],objects:['jaguar'],emotions:['alert']},
    '3afab320f6653cc7b5bdc7d675b0e05e74f832c4c7009ab856aff06b3a64b08f':{description:'A narrow hiking trail crossing a green alpine mountainside.',colors:['green','blue','gray'],tags:['landscape','mountain','trail','travel'],objects:['mountain','trail','trees'],emotions:['peaceful']},
    '3b2fbef7bad03fc66fd0cb41a60984c687e3e4da373d4e139794f5ca014d2fd8':{description:'Several pigeons walking inside a wooden gravel-floored enclosure.',colors:['brown','gray'],tags:['birds','enclosure'],objects:['pigeons','wooden wall'],emotions:[]},
    '4020ff39b3bb95d9fa24e8cd197968e81d1008eb4e06c3e9decd024b9a137d7a':{description:'A wide view of Vidhana Soudha beneath a bright blue and cloudy sky.',colors:['blue','white','gold'],tags:['architecture','landmark','city','travel'],objects:['government building','road'],emotions:[]},
    '40d2d1a623d1e423e82880ae5e8035b5fb79a6f3ba74391436126d721f74781e':{description:'A smiling newlywed couple walking through falling confetti.',colors:['white','gray','pink'],tags:['wedding','people','celebration','portrait'],objects:['bride','groom','confetti'],emotions:['joy']},
    '4509b7b748cc69e6b3686446640c39ee642d446b696757d0764bc71e8c182df7':{description:'A dry open savanna with distant rocky mountains beneath a clear sky.',colors:['tan','blue','gray'],tags:['landscape','savanna','mountain','travel'],objects:['field','mountains'],emotions:['quiet']},
    '4f708c9bed54f71bfc35bac18165e71c7a9c78d9a459258f893bc5a2b0f2b10a':{description:'A brightly illuminated city skyline reflected across water at night.',colors:['black','blue','orange'],tags:['city','night','skyline','reflection'],objects:['buildings','water'],emotions:['vibrant']},
    '5e9f1ddc582220d43aaf5b507455c9c4987e7d1cf06667acb79f4181559f14d6':{description:'Dark storm clouds and turbulent blue water across the open ocean.',colors:['blue','gray','black'],tags:['ocean','storm','landscape','weather'],objects:['waves','clouds'],emotions:['dramatic']},
    '5f97f877ae970f3d58868dcac3978d0312ab39c38f0b1f9a3b1e5d6c941334ad':{description:'A rugged mountain peak with patches of snow beneath a clear blue sky.',colors:['blue','gray','white'],tags:['mountain','snow','landscape'],objects:['mountain','snow'],emotions:['calm']},
    '6110db8f279ff20b056cafcc59b781b660d81f96e05dd072174c318d34196e9f':{description:'Snow-capped alpine mountains reflected in a still lake at golden hour.',colors:['blue','brown','white'],tags:['mountain','lake','reflection','landscape'],objects:['mountains','lake','trees'],emotions:['peaceful']}
  };
  items.forEach(item=>{item.sensitive=false;item.scan={description:'',colors:[],tags:[],objects:[],emotions:[]};item.tags=['standard'];item.analysisSource='browser'});
  let searchHistory=[],vaultFilter='all';
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));

  function libraryItems(){const hide=q('#hide-sensitive')?.checked??true;return items.filter(item=>!hide||!item.sensitive)}
  function expandedTokens(value){const tokens=value.toLowerCase().trim().split(/\s+/).filter(Boolean),expanded=new Set(tokens);for(const token of tokens)for(const group of semanticGroups)if(group.includes(token))group.forEach(word=>expanded.add(word));return [...expanded]}
  function smartResults(value,data=libraryItems()){
    const tokens=expandedTokens(value);if(!tokens.length)return data;
    return data.map(item=>{const name=item.name.toLowerCase(),tags=item.tags.join(' ').toLowerCase();let score=0;for(const token of tokens){if(name.includes(token))score+=5;if(tags.includes(token))score+=2}return{item,score}}).filter(result=>result.score).sort((a,b)=>b.score-a.score).map(result=>result.item)
  }
  function renderLibrary(record=false){const value=q('#search').value.trim(),results=smartResults(value),target=q('#gallery');if(results.length)gallery(target,results);else target.innerHTML=`<div class="empty card gallery-empty"><h2>${value?'No matching media':'Your library is empty'}</h2><p>${value?'Album found no sufficiently relevant matches. Try fewer descriptive words or check the spelling.':'Add a folder in Settings to start building your private archive.'}</p>${value?'':'<button class="button primary" id="empty-add-folder">Add folder</button>'}</div>`;const status=q('.status');if(status)status.textContent=value?`${results.length} ${results.length===1?'match':'matches'}`:`Ready · ${items.length} indexed ${items.length===1?'file':'files'}`;q('#empty-add-folder')?.addEventListener('click',()=>q('#file-input').click());if(record&&value){searchHistory=[value,...searchHistory.filter(entry=>entry!==value)].slice(0,8)}}
  q('#search').placeholder='Search anything';q('#search').oninput=()=>renderLibrary();q('#search-button').onclick=()=>renderLibrary(true);q('#search').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();renderLibrary(true)}};
  q('#search-history').onclick=()=>{if(!searchHistory.length){toast('No recent searches');return}modal('Recent searches',searchHistory.join(' · '),'Close')};
  q('#hide-sensitive').onchange=()=>{renderLibrary();toast(q('#hide-sensitive').checked?'Sensitive media hidden from Library':'Sensitive media visible in Library')};renderLibrary();

  function vaultItems(){const query=q('#vault-search').value.toLowerCase().trim();return items.filter(item=>item.sensitive&&(!query||`${item.name} ${item.tags.join(' ')}`.toLowerCase().includes(query))&&(vaultFilter==='all'||item.tags.includes(vaultFilter)))}
  function renderVault(){const data=vaultItems(),target=q('#vault-gallery'),query=q('#vault-search').value.trim();if(data.length)gallery(target,data);else target.innerHTML=`<div class="empty card gallery-empty"><h2>${query||vaultFilter!=='all'?'No matching media':'Your vault is empty'}</h2><p>${query||vaultFilter!=='all'?'Nothing in your Vault matches this category and search.':'Files classified as sensitive, or items you manually mark as sensitive, will appear here.'}</p></div>`}
  q('#vault-search').oninput=renderVault;q('#vault-filters').onclick=event=>{const button=event.target.closest('[data-vault-filter]');if(!button)return;vaultFilter=button.dataset.vaultFilter;qa('#vault-filters .chip').forEach(chip=>chip.classList.toggle('selected',chip===button));renderVault()};
  q('#vault-search-button').onclick=renderVault;q('#vault-search-history').onclick=()=>toast('No recent Vault searches');q('#vault-layout-button').onclick=()=>{const target=q('#vault-gallery'),square=target.classList.toggle('square-gallery');q('#vault-layout-button .material-symbols-rounded').textContent=square?'view_quilt':'grid_view'};renderVault();

  q('#viewer-share').onclick=()=>{const item=items[current],link=document.createElement('a');link.href=item.src;link.download=`${item.name}.jpg`;link.click();toast('Image copy saved')};
  async function openPhotoInfo(){
    const item=items[current],response=await fetch(item.src),bytes=await response.arrayBuffer(),image=new Image();image.src=item.src;await image.decode();
    const digest=await crypto.subtle.digest('SHA-256',bytes),hash=[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');
    const data=item.scan||{description:'',colors:[],tags:[],objects:[],emotions:[]},dialog=q('#modal');dialog.classList.add('metadata-dialog');
    const tagRow=(label,key,values)=>`<div class="metadata-tag-field"><span>${label}</span><div class="metadata-tags" data-metadata-tags="${key}">${values.map(value=>`<button type="button" data-tag="${escapeHtml(value)}">${escapeHtml(value)}</button>`).join('')}<button type="button" class="metadata-add-tag" aria-label="Add ${label} tag">+</button></div></div>`;
    const fileName=item.fileName||`${item.id}.jpg`,location=item.relativePath||`assets/${fileName}`,analysis=item.analysisSource==='browser'?'Browser metadata scan (full AI unavailable without Album service)':'Album sample analysis';
    q('#modal-body').innerHTML=`<div class="metadata-head"><div><h2>Photo information</h2><p>Correct what Album understood. Saved corrections remain authoritative during later rescans.</p></div><button class="button" id="metadata-rescan" type="button"><span class="material-symbols-rounded">search</span>Rescan with latest learning</button></div><div class="metadata-scroll"><section class="metadata-card"><h3>What Album understands</h3><label>Detailed description<textarea id="metadata-description">${escapeHtml(data.description)}</textarea></label><label>Visible text and signatures<textarea id="metadata-ocr" placeholder="No information recorded">${escapeHtml(data.ocr||'')}</textarea></label><label>Searchable index text<textarea id="metadata-search">${escapeHtml(item.tags.filter(tag=>tag!=='standard').join(' '))}</textarea></label></section><section class="metadata-card"><h3>Tags</h3><p>Colors identify what a tag means. Click a tag to edit or remove it; use + to add one.</p>${tagRow('Colors','colors',data.colors||[])}${tagRow('Semantic tags','tags',data.tags||[])}${tagRow('Recognized-object tags','objects',data.objects||[])}${tagRow('Face-emotion tags','emotions',data.emotions||[])}</section><section class="metadata-card"><h3>Technical details</h3><pre>File: ${escapeHtml(fileName)}\nLocation: ${escapeHtml(location)}\nDimensions: ${image.naturalWidth} × ${image.naturalHeight}\nSize: ${(bytes.byteLength/1048576).toFixed(2)} MB\nMIME: ${item.mime||response.headers.get('content-type')||'image/jpeg'}\nSHA-256: ${item.sha256||hash}\nClassification: ${item.sensitive?'Sensitive':'Standard'}\nAnalysis: ${analysis}\nIndexed search text: ${escapeHtml(item.tags.filter(tag=>tag!=='standard').join(' '))}</pre></section></div><div class="metadata-actions"><button class="button" value="cancel">Cancel</button><button class="button primary" id="metadata-save" type="button">Save corrections</button></div>`;
    dialog.querySelector('form').onsubmit=null;
    dialog.showModal();
    const values=()=>Object.fromEntries(['colors','tags','objects','emotions'].map(key=>[key,[...q(`[data-metadata-tags="${key}"]`).querySelectorAll('[data-tag]')].map(button=>button.dataset.tag)]));
    const renderTags=(key,list)=>{const row=q(`[data-metadata-tags="${key}"]`),add=row.querySelector('.metadata-add-tag');row.querySelectorAll('[data-tag]').forEach(button=>button.remove());for(const value of list){const button=document.createElement('button');button.type='button';button.dataset.tag=value;button.textContent=value;row.insertBefore(button,add)}};
    q('.metadata-scroll').onclick=event=>{const add=event.target.closest('.metadata-add-tag'),tag=event.target.closest('[data-tag]');if(add){const value=prompt('Add tag:','')?.trim().toLowerCase();if(value){const row=add.parentElement,current=[...row.querySelectorAll('[data-tag]')].map(button=>button.dataset.tag);if(!current.includes(value))renderTags(row.dataset.metadataTags,[...current,value])}}else if(tag){const value=prompt('Edit tag (leave blank to remove):',tag.dataset.tag);const row=tag.parentElement,current=[...row.querySelectorAll('[data-tag]')].map(button=>button.dataset.tag);renderTags(row.dataset.metadataTags,value?.trim()?[...current.filter(entry=>entry!==tag.dataset.tag),value.trim().toLowerCase()]:current.filter(entry=>entry!==tag.dataset.tag))}};
    q('#metadata-rescan').onclick=()=>{if(item.analysisSource==='browser'){toast('Full AI rescanning requires the local Album analysis service');return}const button=q('#metadata-rescan'),updated=values();item.scan={...data,...updated,description:q('#metadata-description').value.trim(),ocr:q('#metadata-ocr').value.trim()};button.disabled=true;button.textContent='Rescanning…';setTimeout(()=>{button.disabled=false;button.innerHTML='<span class="material-symbols-rounded">search</span>Rescan with latest learning';toast('Sample analysis refreshed; saved corrections were preserved')},450)};
    q('#metadata-save').onclick=()=>{const updated=values();item.scan={...data,...updated,description:q('#metadata-description').value.trim(),ocr:q('#metadata-ocr').value.trim()};item.tags=[...new Set([...updated.colors,...updated.tags,...updated.objects,...updated.emotions,...q('#metadata-search').value.toLowerCase().split(/\s+/).filter(Boolean),'standard'])];dialog.close();dialog.classList.remove('metadata-dialog');renderLibrary();toast('Photo information saved')};
    dialog.addEventListener('close',()=>dialog.classList.remove('metadata-dialog'),{once:true});
  }
  q('#viewer-info').onclick=()=>openPhotoInfo().catch(()=>toast('Photo information could not be loaded'));
  q('#viewer-more').onclick=()=>modal('More options','Mark as sensitive or standard, organize in the Vault, open in another app, or reveal the original file.','Close');

  const collections=[];
  function paintCollections(){const list=q('#collections-list');if(!collections.length){list.innerHTML='<div class="empty card"><h2>No collections yet</h2><p>Create albums and virtual groupings.</p><button class="button primary" id="empty-create-collection">Create collection</button></div>';q('#empty-create-collection').onclick=()=>q('#new-collection').click();return}list.innerHTML=collections.map((collection,index)=>`<article class="collection card" tabindex="0" data-collection="${index}"><div class="collection-art">${collection.items.slice(0,3).map(item=>`<img src="${item.src}" alt="">`).join('')}</div><h2>${escapeHtml(collection.name)}</h2><p>${collection.items.length} ${collection.items.length===1?'item':'items'}</p></article>`).join('');list.onclick=event=>{const card=event.target.closest('[data-collection]');if(!card)return;const collection=collections[+card.dataset.collection];switchPage('library');gallery(q('#gallery'),collection.items);q('#search').value='';q('.status').textContent=`${collection.name} · ${collection.items.length} ${collection.items.length===1?'item':'items'}`};}
  paintCollections();
  q('#new-collection').onclick=()=>{q('#modal-body').innerHTML='<h2>New collection</h2><p>Create a collection from the currently selected library items.</p><input id="collection-name" placeholder="Collection name" autofocus><div style="display:flex;justify-content:flex-end;gap:8px"><button class="button" value="cancel">Cancel</button><button class="button primary" id="create-collection" type="button">Create collection</button></div>';q('#modal').showModal();q('#create-collection').onclick=()=>{const value=q('#collection-name').value.trim();if(!value)return;collections.push({name:value,items:items.filter(item=>item.selected)});q('#modal').close();paintCollections();toast(`${value} created`)}};

  q('.private-label').textContent='PRIVATE';
  const selectionBar=document.createElement('div');selectionBar.className='selection-bar';selectionBar.hidden=true;selectionBar.innerHTML='<strong id="selection-count">0 selected</strong><span></span><button class="text-button" data-selection-action="share">Share</button><button class="text-button" data-selection-action="collection">Add to collection</button><button class="text-button" data-selection-action="favorite">Favorite</button><button class="text-button" data-selection-action="vault">Move to Vault</button><button class="text-button danger" data-selection-action="delete">Delete</button><button class="bare-icon" data-selection-action="clear" aria-label="Clear selection"><span class="material-symbols-rounded">close</span></button>';
  q('#library').insertBefore(selectionBar,q('.library-search'));
  function syncSelection(){const selected=items.filter(item=>item.selected);selectionBar.hidden=!selected.length;q('#selection-count').textContent=`${selected.length} selected`}
  document.addEventListener('album-selection-change',syncSelection);selectionBar.onclick=event=>{const action=event.target.closest('[data-selection-action]')?.dataset.selectionAction,selected=items.filter(item=>item.selected);if(!action)return;if(action==='clear'){selected.forEach(item=>item.selected=false);renderLibrary();syncSelection()}else if(action==='vault'){selected.forEach(item=>item.sensitive=true);renderLibrary();syncSelection();toast(`${selected.length} moved to Vault`)}else if(action==='favorite'){selected.forEach(item=>item.tags=[...new Set([...item.tags,'favorite'])]);toast(`${selected.length} favorited`)}else if(action==='collection'){switchPage('collections');q('#new-collection').click()}else if(action==='share'){toast('Use Share from a single photo to export its original file')}else if(action==='delete'){toast('Web portfolio never deletes original files')}};

  function renderKinds(){for(const [page,kind,noun,detail] of [['video','video','videos','Videos from your library folders will appear here.'],['audio','audio','audio','Audio from your library folders will appear here.'],['documents','document','documents','Documents from your library folders will appear here.']]){const section=q(`#${page}`),data=items.filter(item=>item.kind===kind),existing=section.querySelector('.empty,.gallery');if(existing)existing.outerHTML=data.length?`<div class="gallery" id="${page}-gallery"></div>`:`<div class="empty card"><h2>No ${noun} yet</h2><p>${detail}</p><button class="button primary" data-empty-folder>Add folder</button></div>`;if(data.length)gallery(q(`#${page}-gallery`),data);else section.querySelector('[data-empty-folder]').onclick=()=>q('#file-input').click()}}

  q('.settings-stack').innerHTML='<article class="card settings-card"><div><h2>People &amp; Pets</h2><p>Control conservative automatic grouping of recognized people and pets.</p><label class="check"><input id="combine-identities" type="checkbox" checked> Combine high-confidence matches automatically</label></div></article><article class="card settings-card"><div><h2>Library sources</h2><p>Choose folders for Album to scan. Album only scans folders you approve.</p><div id="source-list"></div></div><div class="settings-actions"><button class="button" id="refresh-sources">Refresh</button><button class="button primary" id="settings-add"><span class="material-symbols-rounded">add</span>Add folder</button></div></article><article class="card settings-card"><div><h2>Gallery dates</h2><p>Choose which available date organizes the library.</p></div><select><option>Photo taken (EXIF)</option><option>File created on this computer</option><option>Added to Album</option></select></article><article class="card settings-card"><div><h2>Privacy</h2><label class="check"><input id="hide-sensitive" type="checkbox" checked> Hide sensitive media from the main library</label><p>Hidden media remains available in your Vault.</p></div><button class="button" id="set-password">Set or change password</button></article><article class="card settings-card"><div><h2>Duplicate review</h2><p>Compare likely copies and safely decide which file to keep.</p></div><button class="button" id="review-duplicates">Review duplicates</button></article><article class="card settings-card"><div><h2>Organize files</h2><p>Optional: copy or move files only after explicit confirmation.</p></div><button class="button" id="organize-files">Organize files</button></article><article class="card settings-card"><div><h2>Backup &amp; recovery</h2><p>Back up, restore, verify, or rebuild Album’s local catalog.</p></div><div class="settings-actions"><button class="button">Back up</button><button class="button">Restore</button><button class="button">Verify</button><button class="button">Rebuild</button></div></article><article class="card settings-card"><div><h2>Learning &amp; corrections</h2><p>Export the corrections Album uses to improve later rescans.</p></div><button class="button">Export</button></article><article class="card settings-card"><div><h2>Linked devices</h2><p>Pair a trusted phone or computer, or revoke an existing device.</p></div><button class="button primary" id="pair-device">Link a device</button></article><article class="card settings-card"><div><h2>Credits &amp; licenses</h2><p>Review Album and model licenses.</p></div><button class="button">View credits</button></article>';
  const sources=[];function paintSources(){q('#source-list').innerHTML=sources.length?sources.map(source=>`<div class="folder-row"><span class="material-symbols-rounded">folder</span><span>${escapeHtml(source)}</span><button class="text-button" data-remove-source="${escapeHtml(source)}">Remove access</button></div>`).join(''):'<p class="muted source-empty">No folders approved in this browser session.</p>'}paintSources();
  q('#settings-add').onclick=q('#add-media').onclick=()=>q('#file-input').click();q('#refresh-sources').onclick=()=>toast(sources.length?'Refreshing approved folders…':'No approved folders to refresh');q('#source-list').onclick=event=>{const source=event.target.closest('[data-remove-source]')?.dataset.removeSource;if(!source)return;sources.splice(sources.indexOf(source),1);paintSources();toast('Folder access removed')};q('#set-password').onclick=()=>modal('Set Vault password','A production deployment must store only a salted password hash; this portfolio build does not retain passwords.','Close');q('#pair-device').onclick=()=>modal('Link a device','Pairing requires the authenticated local Album service and a time-limited single-use code.','Close');q('#review-duplicates').onclick=()=>modal('Duplicate review','No duplicate suggestions are available in the current browser catalog.','Close');q('#organize-files').onclick=()=>modal('Organize files into Album','Browser security prevents a portfolio page from moving originals without explicit file-system permission.','Close');

  async function digestFile(file){const bytes=await file.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
  function fileKind(file){if(file.type.startsWith('image/'))return'image';if(file.type.startsWith('video/'))return'video';if(file.type.startsWith('audio/'))return'audio';return'document'}
  async function inspectImage(file,url){const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas'),size=48;canvas.width=canvas.height=size;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,size,size);const pixels=context.getImageData(0,0,size,size).data;let red=0,green=0,blue=0,count=0;for(let index=0;index<pixels.length;index+=16){red+=pixels[index];green+=pixels[index+1];blue+=pixels[index+2];count++}return{width:image.naturalWidth,height:image.naturalHeight,averageColor:`rgb(${Math.round(red/count)}, ${Math.round(green/count)}, ${Math.round(blue/count)})`}}
  async function importFiles(fileList){const files=[...fileList].filter(file=>file.type.startsWith('image/')||file.type.startsWith('video/')||file.type.startsWith('audio/')||/\.(txt|md|pdf)$/i.test(file.name));if(!files.length){toast('No supported files selected');return}const status=q('.status');for(let index=0;index<files.length;index++){const file=files[index],url=URL.createObjectURL(file),kind=fileKind(file);status.textContent=`Scanning ${index+1} of ${files.length}: ${file.name}`;const item={id:crypto.randomUUID(),name:file.name,fileName:file.name,relativePath:file.webkitRelativePath||file.name,src:url,file,kind,sensitive:false,tags:[],selected:false,size:file.size,mime:file.type,lastModified:file.lastModified,sha256:await digestFile(file),analysisSource:'browser',scan:{description:'',colors:[],tags:[],objects:[],emotions:[]}};if(kind==='image')Object.assign(item,await inspectImage(file,url));items.unshift(item);const root=(file.webkitRelativePath||'').split('/')[0];if(root&&!sources.includes(root))sources.push(root)}paintSources();renderLibrary();renderKinds();toast(`${files.length} ${files.length===1?'file':'files'} scanned locally`)}
  q('#file-input').onchange=async event=>{await importFiles(event.target.files);event.target.value=''};
  q('#hide-sensitive').onchange=()=>{renderLibrary();toast(q('#hide-sensitive').checked?'Sensitive media hidden from Library':'Sensitive media visible in Library')};
  Promise.all(items.map(async item=>{try{const response=await fetch(item.src),blob=await response.blob(),file=new File([blob],item.fileName,{type:blob.type});item.size=blob.size;item.mime=blob.type;item.sha256=await digestFile(file);Object.assign(item,await inspectImage(file,item.src))}catch{}})).then(()=>renderLibrary());
})();
